# Velocity to Discordを導入してくれてありがとう！
# わたしはあなたに感謝します！
# Bugやフィードバックの報告については下記URLから。

# Thanks for introducing "Velocity to Discord"!
# Thanks for you!
# Please use the following URL to report bugs and provide feedback.

# Discord:https://discord.gg/5sqbsmqd6K
# Github:https://github.com/Elysium-7/Velocity-to-Discord

# ここは絶対に書き換えないでください。
# Never rewrite this section.
configuration-version: 1.2

# BotTokenを入力。
# Please insert a BotToken.
token: ""

# BOTのスタータスを設定できます。「ONLINE,IDLE,DO_NOT_DISTURB」
# You can set the bot online status "ONLINE,IDLE,DO_NOT_DISTURB"
online_status: ONLINE

# ログを送信するチャンネルのIDを入力してね。
# Enter the ID of the channel you want to send the log to.
channel_id: 0

# サーバースタート・ストップ時のメッセージを編集できます。
# You can edit messages at server start/stop.
start_message_text: "Server has started."
stop_message_text: "Server has stopped."
